name: Ruff linter for Python
description: Run ruff linter on given target or default.

inputs:
  target:
    description: Lint target for ruff.
    required: false
    default: .

runs:
  using: "composite"

  steps:
    - name: Poetry install
      uses: wintero92/poetry-install-action@v1

    - name: Ruff
      shell: bash
      run: |
        source .venv/bin/activate
        ruff check ${{inputs.target}}
